<script setup>
import {ref,onMounted,computed} from 'vue'; import {useRouter} from 'vue-router'; import {onAuthStateChanged,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut} from 'firebase/auth'; import {auth,googleProvider} from './firebase'; import {ensureUser} from './services/data';
const router=useRouter(),user=ref(null),profile=ref(null),email=ref(''),password=ref(''),busy=ref(false),error=ref(''),theme=ref(localStorage.getItem('fs-theme')||'dark'),menu=ref(false); const toast=ref('');
const nav=[['/','Ana Sayfa','⌂'],['/apps','Uygulamalar','▣'],['/community','Topluluk','♟'],['/chat','Açık Sohbet','☵'],['/clans','Klanlar','♜'],['/inbox','Gelen Gidenler','✉'],['/publish','Yayınla','＋'],['/storage','Depolama','↗'],['/profile','Profil','◉'],['/rules','Kurallar','!'],['/settings','Ayarlar','⚙'],['/moderation','Moderatör','🛡'],['/developer','Developer','🔥']];
const isDark=computed(()=>theme.value==='dark'); function toggleTheme(){theme.value=isDark.value?'light':'dark';localStorage.setItem('fs-theme',theme.value)}
async function authCall(fn){busy.value=true;error.value='';try{const r=await fn(); profile.value=await ensureUser(r.user); menu.value=false}catch(e){error.value=human(e)}finally{busy.value=false}} const login=()=>authCall(()=>signInWithEmailAndPassword(auth,email.value,password.value)); const register=()=>authCall(()=>createUserWithEmailAndPassword(auth,email.value,password.value)); const google=()=>authCall(()=>signInWithPopup(auth,googleProvider)); function human(e){return e.code==='auth/invalid-credential'?'E-posta veya şifre hatalı.':e.code==='auth/email-already-in-use'?'Bu e-posta zaten kayıtlı.':e.message||'Bir hata oluştu.'}
function notify(t){toast.value=t;setTimeout(()=>toast.value='',3000)} onMounted(()=>onAuthStateChanged(auth,async u=>{user.value=u;profile.value=u?await ensureUser(u):null}));
</script>
<template><div class="app" :data-theme="theme"><header class="top"><button class="brand" @click="router.push('/')"><span>🔥</span> FlameStore</button><div class="top-actions"><button class="icon-btn" @click="toggleTheme" :title="isDark?'Açık tema':'Koyu tema'">{{isDark?'☀':'☾'}}</button><button v-if="user" class="avatar-btn" @click="menu=!menu"><img v-if="profile?.photoURL" :src="profile.photoURL"><span v-else>{{profile?.displayName?.slice(0,1)}}</span></button></div><div v-if="menu" class="user-menu"><b>{{profile?.displayName}}</b><small>{{profile?.role}}</small><button @click="router.push('/profile');menu=false">Profil</button><button @click="signOut(auth);menu=false">Çıkış yap</button></div></header>
<div class="layout"><aside class="sidebar"><nav><button v-for="n in nav" :key="n[0]" @click="router.push(n[0])" :class="{active:router.currentRoute.value.path===n[0]}"><span>{{n[2]}}</span>{{n[1]}}</button></nav></aside><main class="content"><div v-if="!user" class="auth-card card"><div class="flame-mark">🔥</div><h1>FlameStore</h1><p class="muted">Ateş gibi hızlı. Topluluk kadar sosyal.</p><div class="auth-tabs"><b>Giriş / Kayıt</b></div><input v-model="email" class="field" type="email" placeholder="E-posta"><input v-model="password" class="field" type="password" placeholder="Şifre"><button class="btn primary full" :disabled="busy" @click="login">{{busy?'Bekle...':'Giriş yap'}}</button><button class="btn secondary full" @click="register">E-posta ile kayıt ol</button><div class="or"><span>veya</span></div><button class="btn google full" @click="google">G Google ile devam et</button><p class="danger" v-if="error">{{error}}</p></div><router-view v-else-if="router.currentRoute.value.path==='/moderation'" :user="user" :profile="profile" @toast="notify"/><router-view v-else-if="router.currentRoute.value.path==='/developer'" :user="user" :profile="profile" @toast="notify"/><router-view v-else :user="user" :profile="profile" @toast="notify"/></main></div><nav class="mobile-nav"><button v-for="n in nav.slice(0,5)" :key="n[0]" @click="router.push(n[0])" :class="{active:router.currentRoute.value.path===n[0]}"><span>{{n[2]}}</span>{{n[1]}}</button></nav><div v-if="toast" class="toast">{{toast}}</div></div></template>