<script setup>
import {ref,onMounted,onUnmounted,computed} from 'vue';import {collection,addDoc,onSnapshot,query,orderBy,serverTimestamp,doc,updateDoc,arrayUnion} from 'firebase/firestore';import {db} from '../firebase';import {uploadSmall,watchClanMessages,addClanMessage,watchClanInvites} from '../services/data';import {httpsCallable} from 'firebase/functions';import {functions} from '../firebase';
const props=defineProps(['user','profile']);const emit=defineEmits(['toast']);const name=ref(''),photo=ref(null),clans=ref([]),selected=ref(null),messages=ref([]),message=ref(''),inviteName=ref(''),invites=ref([]);let stop,stopMsg,stopInv;
onMounted(()=>{stop=onSnapshot(query(collection(db,'clans'),orderBy('createdAt','desc')),s=>clans.value=s.docs.map(d=>({id:d.id,...d.data()})));stopInv=watchClanInvites(props.user.uid,v=>invites.value=v)});onUnmounted(()=>{stop?.();stopMsg?.();stopInv?.()});
async function create(){if(!name.value.trim())return emit('toast','Klan adı gerekli.');try{let imageUrl='';if(photo.value)imageUrl=await uploadSmall(props.user.uid,photo.value,'clans');await addDoc(collection(db,'clans'),{name:name.value.trim(),imageUrl,ownerId:props.user.uid,members:[props.user.uid],createdAt:serverTimestamp()});name.value='';photo.value=null;emit('toast','Klan oluşturuldu.')}catch(e){emit('toast',e.message)}}
function openClan(c){selected.value=c;stopMsg?.();stopMsg=watchClanMessages(c.id,v=>messages.value=v)}
async function send(){const t=message.value.trim();if(!t||!selected.value)return;await addClanMessage(selected.value.id,{uid:props.user.uid,author:props.profile.displayName,text:t});message.value=''}
async function invite(){if(!selected.value||!inviteName.value.trim())return;try{await httpsCallable(functions,'inviteToClan')({clanId:selected.value.id,username:inviteName.value.trim()});inviteName.value='';emit('toast','Klan daveti gönderildi.')}catch(e){emit('toast',e.message)}}async function accept(i){try{await httpsCallable(functions,'respondClanInvite')({inviteId:i.id,accept:true});emit('toast','Klan daveti kabul edildi.')}catch(e){emit('toast',e.message)}}
const mine=computed(()=>clans.value.filter(c=>c.members?.includes(props.user.uid)));
</script><template><div class="space"><div><h1>♜ Klanlar</h1><p class="muted">Klan kur, üyelerini yönet ve gerçek zamanlı sohbet et.</p></div></div><div v-if="invites.length" class="card"><h2>📨 Gelen Klan Davetleri</h2><div v-for="i in invites" :key="i.id" class="list-item"><div><b>{{i.clanName}}</b><span class="muted"> · {{i.fromName}}</span></div><button class="btn" @click="accept(i)">Kabul et</button></div></div><br><div class="card"><h2>Klan oluştur</h2><input class="field" v-model="name" maxlength="40" placeholder="Klan adı"><input class="field" type="file" accept="image/*" @change="photo=$event.target.files[0]||null"><button class="btn" @click="create">Oluştur</button></div><br><div class="apps-grid"><div v-for="c in clans" :key="c.id" class="card"><img v-if="c.imageUrl" :src="c.imageUrl" class="banner"><h2>{{c.name}}</h2><div class="tags"><span class="tag">♟ {{c.members?.length||0}} üye</span></div><button class="btn secondary" @click="openClan(c)">Sohbete gir</button></div></div><div v-if="selected" class="card clan-chat"><div class="space"><h2>💬 {{selected.name}}</h2><button class="mini-btn" @click="selected=null">Kapat</button></div><div class="invite-row"><input class="field" v-model="inviteName" placeholder="Davet edilecek kullanıcı adı"><button class="btn secondary" @click="invite">Davet</button></div><div class="chat-box"><div v-for="m in messages" :key="m.id" class="chat-msg"><b>{{m.author}}</b><span>{{m.text}}</span></div></div><div class="comment-compose"><input class="field" v-model="message" @keyup.enter="send" placeholder="Klana mesaj yaz..."><button class="btn" @click="send">Gönder</button></div></div></template>
