<script setup>
import {ref,onMounted,onUnmounted,computed} from 'vue';import {createPost,watchPosts,toggleLike,deletePost,addReport,uploadSmall,watchComments,addComment,deleteComment} from '../services/data';
const props=defineProps(['user','profile']);const emit=defineEmits(['toast']);const text=ref(''),image=ref(null),posts=ref([]),sort=ref('new'),busy=ref(false),comments=ref({}),commentText=ref({}),openComments=ref({});let stop;
function load(){stop?.();stop=watchPosts(v=>posts.value=v,sort.value)}onMounted(load);onUnmounted(()=>stop?.());
async function post(){if(!text.value.trim()&&!image.value)return;busy.value=true;try{let imageUrl='';if(image.value)imageUrl=await uploadSmall(props.user.uid,image.value,'posts');await createPost({uid:props.user.uid,author:props.profile.displayName,photoURL:props.profile.photoURL||'',text:text.value.trim(),imageUrl});text.value='';image.value=null;emit('toast','Gönderi paylaşıldı.')}catch(e){emit('toast',e.message)}finally{busy.value=false}}
async function report(p){await addReport({reporterUid:props.user.uid,targetType:'post',targetId:p.id,targetUid:p.uid,reason:'Topluluk bildirimi'});emit('toast','Rapor alındı.')}
async function remove(p){if(confirm('Gönderi silinsin mi?'))await deletePost(p.id)}
function loadComments(p){openComments.value[p.id]=!openComments.value[p.id];if(openComments.value[p.id]&&!comments.value[p.id])watchComments(p.id,v=>comments.value[p.id]=v)}
async function comment(p){const t=(commentText.value[p.id]||'').trim();if(!t)return;await addComment(p.id,{uid:props.user.uid,author:props.profile.displayName,photoURL:props.profile.photoURL||'',text:t});commentText.value[p.id]='';emit('toast','Yorum eklendi.')}
async function removeComment(p,c){if(confirm('Yorum silinsin mi?'))await deleteComment(p.id,c.id)}
const canMod=computed(()=>['DEVELOPER','MODERATOR'].includes(props.profile?.role));
</script>
<template><div class="space"><div><h1>Topluluk</h1><p class="muted">Paylaş, keşfet, yorumla ve topluluğa katıl.</p></div><select class="field" style="width:auto" v-model="sort" @change="load"><option value="new">En Yeni</option><option value="likes">En Çok Beğenilen</option></select></div>
<div class="card"><textarea class="field" rows="4" v-model="text" maxlength="2000" placeholder="Ne düşünüyorsun? @kullanıcıadı ile etiketleyebilirsin."></textarea><input class="field" type="file" accept="image/*" @change="image=$event.target.files[0]||null"><div class="space"><small class="muted">{{text.length}}/2000</small><button class="btn" :disabled="busy" @click="post">{{busy?'Paylaşılıyor...':'Paylaş'}}</button></div></div><br>
<div v-for="p in posts" :key="p.id" class="card" style="margin-bottom:14px"><div class="space"><div><b>{{p.author}}</b><div class="muted" style="font-size:12px">FlameStore topluluk üyesi</div></div><span>{{p.likesCount||0}} ❤️</span></div><p style="white-space:pre-wrap">{{p.text}}</p><img v-if="p.imageUrl" :src="p.imageUrl" class="post-image"><div class="row"><button class="btn secondary" @click="toggleLike(p.id,props.user.uid,(p.likes||[]).includes(props.user.uid))">❤️ Beğen</button><button class="btn secondary" @click="loadComments(p)">💬 {{p.commentsCount||0}} Yorum</button><button class="btn secondary" @click="report(p)">⚑ Raporla</button><button v-if="canMod" class="btn secondary" @click="remove(p)">Sil</button></div>
<div v-if="openComments[p.id]" class="comments"><div class="comment-compose"><input class="field" v-model="commentText[p.id]" maxlength="500" placeholder="Yorum yaz..."><button class="btn" @click="comment(p)">Gönder</button></div><div v-for="c in (comments[p.id]||[])" :key="c.id" class="comment"><div><b>{{c.author}}</b><span class="muted"> · {{c.text}}</span></div><button v-if="canMod||c.uid===user.uid" class="mini-btn" @click="removeComment(p,c)">Sil</button></div><div v-if="comments[p.id]&&!comments[p.id].length" class="muted">Henüz yorum yok.</div></div></div><div v-if="!posts.length" class="card empty">Henüz gönderi yok.</div></template>
