const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {onDocumentCreated}=require('firebase-functions/v2/firestore');
const admin=require('firebase-admin');admin.initializeApp();const db=admin.firestore();
const REGION='europe-west1',DEV_EMAIL='mustafamirac000@gmail.com';
function assertAuth(req){if(!req.auth)throw new HttpsError('unauthenticated','Giriş gerekli.');}
async function roleOf(uid){return (await db.doc(`users/${uid}`).get()).data()?.role||'USER';}
async function assertStaff(uid){const r=await roleOf(uid);if(!['DEVELOPER','MODERATOR','GUIDE'].includes(r))throw new HttpsError('permission-denied','Yetkin yok.');return r;}
async function vtScan(url){const key=process.env.VT_API_KEY;if(!key)throw new HttpsError('failed-precondition','VirusTotal anahtarı yapılandırılmamış.');const submit=await fetch('https://www.virustotal.com/api/v3/urls',{method:'POST',headers:{'x-apikey':key,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({url})});if(!submit.ok)throw new HttpsError('unavailable',`VirusTotal isteği başarısız (${submit.status}).`);const body=await submit.json(),id=body.data?.id;if(!id)throw new HttpsError('internal','VirusTotal analiz kimliği alınamadı.');for(let i=0;i<24;i++){await new Promise(r=>setTimeout(r,1500));const res=await fetch(`https://www.virustotal.com/api/v3/analyses/${id}`,{headers:{'x-apikey':key}});if(!res.ok)continue;const j=await res.json();if(j.data?.attributes?.status==='completed'){const st=j.data.attributes.stats||{};return{safe:(st.malicious||0)===0&&(st.suspicious||0)===0,stats:st};}}throw new HttpsError('deadline-exceeded','VirusTotal taraması zaman aşımına uğradı.');}
exports.scanAndPublish=onCall({region:REGION,secrets:['VT_API_KEY'],timeoutSeconds:90,memory:'256MiB'},async req=>{assertAuth(req);const uid=req.auth.uid,d=req.data||{},required=['name','description','category','downloadUrl','storageId','banner'];if(required.some(k=>!d[k]))throw new HttpsError('invalid-argument','Zorunlu yayın alanları eksik.');if(typeof d.downloadUrl!=='string'||!/^https?:\/\//i.test(d.downloadUrl))throw new HttpsError('invalid-argument','Geçerli indirme linki gerekli.');const link=await db.doc(`users/${uid}/storageLinks/${d.storageId}`).get();if(!link.exists)throw new HttpsError('permission-denied','Seçilen depolama bağlantısı sana ait değil.');const scan=await vtScan(d.downloadUrl);if(!scan.safe){await db.collection('moderationActions').add({uid,type:'AUTO_MALWARE_REJECTION',successful:false,reason:'VirusTotal malicious/suspicious result',stats:scan.stats,createdAt:admin.firestore.FieldValue.serverTimestamp()});throw new HttpsError('permission-denied','Zararlı veya şüpheli içerik tespit edildi. Yayın reddedildi.');}const app={uid,name:String(d.name).slice(0,80),description:String(d.description).slice(0,3000),category:String(d.category).slice(0,40),downloadUrl:d.downloadUrl,storageId:d.storageId,banner:d.banner,screenshots:Array.isArray(d.screenshots)?d.screenshots.slice(0,5):[],safe:true,vtStats:scan.stats,downloads:0,ratingTotal:0,ratingCount:0,createdAt:admin.firestore.FieldValue.serverTimestamp()};const ref=await db.collection('apps').add(app);return{safe:true,id:ref.id,stats:scan.stats};});
exports.recalculateLevel=onDocumentCreated({document:'xpEvents/{id}',region:REGION},async e=>{const x=e.data?.data();if(!x?.uid||!Number.isFinite(x.xp))return;const r=db.doc(`users/${x.uid}`);await db.runTransaction(async tx=>{const s=await tx.get(r);if(!s.exists)return;const u=s.data(),xp=Math.max(0,(u.xp||0)+x.xp);tx.update(r,{xp,level:Math.floor(xp/200)+1,updatedAt:admin.firestore.FieldValue.serverTimestamp()});});});
exports.syncDeveloper=onDocumentCreated({document:'users/{uid}',region:REGION},async e=>{const d=e.data?.data();if(d?.email?.toLowerCase()===DEV_EMAIL)await e.data.ref.set({displayName:'Mavi',role:'DEVELOPER'},{merge:true});});
exports.autoRoles=onDocumentCreated({document:'moderationActions/{id}',region:REGION},async e=>{const a=e.data?.data();if(!a?.uid)return;const uid=a.uid,acts=await db.collection('moderationActions').where('uid','==',uid).get(),docs=acts.docs.map(x=>x.data()),successful=docs.filter(x=>x.successful).length,total=docs.length,rate=total?successful/total:0,joined=(await db.doc(`users/${uid}`).get()).data()?.stats?.joinedAt||Date.now(),days=(Date.now()-joined)/86400000,reports=(await db.collection('reports').where('targetUid','==',uid).where('status','==','valid').get()).size;let role=null;if(days>=30&&successful>=25&&rate>=.85&&reports===0)role='MODERATOR';else if(days>=7&&successful>=10&&rate>=.8&&reports===0)role='GUIDE';if(role)await db.doc(`users/${uid}`).set({role,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});});
exports.createAnnouncement=onCall({region:REGION},async req=>{assertAuth(req);if(await roleOf(req.auth.uid)!=='DEVELOPER')throw new HttpsError('permission-denied','Sadece DEVELOPER.');const text=String(req.data?.text||'').slice(0,1000);if(!text)throw new HttpsError('invalid-argument','Duyuru boş olamaz.');const ref=await db.collection('announcements').add({text,authorUid:req.auth.uid,createdAt:admin.firestore.FieldValue.serverTimestamp()});return{id:ref.id};});
exports.moderate=onCall({region:REGION},async req=>{assertAuth(req);const actor=req.auth.uid;await assertStaff(actor);const{targetUid,type,targetId,reason}=req.data||{};if(!targetUid||!type)throw new HttpsError('invalid-argument','Eksik moderasyon bilgisi.');await db.collection('moderationActions').add({uid:targetUid,actorUid:actor,type,targetId:targetId||null,reason:String(reason||'').slice(0,500),successful:true,createdAt:admin.firestore.FieldValue.serverTimestamp()});return{ok:true};});
exports.recordDownload=onCall({region:REGION},async req=>{assertAuth(req);const id=String(req.data?.appId||'');if(!id)throw new HttpsError('invalid-argument','Uygulama ID gerekli.');await db.doc(`apps/${id}`).update({downloads:admin.firestore.FieldValue.increment(1)});return{ok:true};});
exports.rateApp=onCall({region:REGION},async req=>{assertAuth(req);const id=String(req.data?.appId||''),rating=Number(req.data?.rating);if(!id||rating<1||rating>5||!Number.isInteger(rating))throw new HttpsError('invalid-argument','Puan 1-5 arasında olmalı.');const vote=db.doc(`apps/${id}/ratings/${req.auth.uid}`);const app=db.doc(`apps/${id}`);await db.runTransaction(async tx=>{const v=await tx.get(vote),a=await tx.get(app);if(!a.exists)throw new HttpsError('not-found','Uygulama bulunamadı.');if(v.exists)throw new HttpsError('already-exists','Bu uygulamayı daha önce puanladın.');tx.set(vote,{uid:req.auth.uid,rating,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.update(app,{ratingTotal:admin.firestore.FieldValue.increment(rating),ratingCount:admin.firestore.FieldValue.increment(1)});});return{ok:true};});

exports.inviteToClan=onCall({region:REGION},async req=>{assertAuth(req);const uid=req.auth.uid,clanId=String(req.data?.clanId||''),username=String(req.data?.username||'').trim();if(!clanId||!username)throw new HttpsError('invalid-argument','Klan ve kullanıcı adı gerekli.');const clanRef=db.doc(`clans/${clanId}`),clan=(await clanRef.get()).data();if(!clan)throw new HttpsError('not-found','Klan bulunamadı.');if(clan.ownerId!==uid&&!(await roleOf(uid)).match(/^(DEVELOPER|MODERATOR)$/))throw new HttpsError('permission-denied','Sadece klan sahibi veya yetkili davet gönderebilir.');const users=await db.collection('users').where('displayName','==',username).limit(1).get();if(users.empty)throw new HttpsError('not-found','Kullanıcı bulunamadı.');const target=users.docs[0];if((clan.members||[]).includes(target.id))throw new HttpsError('already-exists','Kullanıcı zaten klan üyesi.');await db.collection('clanInvites').add({clanId,clanName:clan.name,fromUid:uid,fromName:(await db.doc(`users/${uid}`).get()).data()?.displayName||'Kullanıcı',toUid:target.id,toName:username,status:'pending',createdAt:admin.firestore.FieldValue.serverTimestamp()});return{ok:true};});
exports.respondClanInvite=onCall({region:REGION},async req=>{assertAuth(req);const inviteId=String(req.data?.inviteId||''),accept=Boolean(req.data?.accept);const invRef=db.doc(`clanInvites/${inviteId}`);const invSnap=await invRef.get();if(!invSnap.exists)throw new HttpsError('not-found','Davet bulunamadı.');const inv=invSnap.data();if(inv.toUid!==req.auth.uid||inv.status!=='pending')throw new HttpsError('permission-denied','Bu davet üzerinde işlem yapamazsın.');if(accept){await db.runTransaction(async tx=>{const clanRef=db.doc(`clans/${inv.clanId}`);const c=await tx.get(clanRef);if(!c.exists)throw new HttpsError('not-found','Klan bulunamadı.');tx.update(clanRef,{members:admin.firestore.FieldValue.arrayUnion(req.auth.uid)});tx.update(invRef,{status:'accepted',respondedAt:admin.firestore.FieldValue.serverTimestamp()});});}else await invRef.update({status:'declined',respondedAt:admin.firestore.FieldValue.serverTimestamp()});return{ok:true};});
